apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: random-number-generator
  name: random-number-generator
spec:
  containers:
  - image: alpine
    name: alpine
    command: ["/bin/sh","c"]
    args: ["shuf -i 0-100 -n 1 >> /opt/number.out"]
    volumeMounts:
      - mountPath: /opt
        name: data-volume
  volumes:
  - name: data-volume
    hostPath:
      path: /tmp
      type: Directory
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
