---
- name: Set Worker Machine Type to large
  ansible.builtin.set_fact:
    machine_type: e2-standard-2
  when: instance_size == "large"

- name: Set Worker Machine Type to xlarge
  ansible.builtin.set_fact:
    machine_type: e2-standard-4
  when: instance_size == "xlarge"

- name: Copy GCP Terraform Directory
  ansible.builtin.copy:
    src: gcp_deploy
    dest: /tmp
    mode: 0777

- name: Initialize Terraform
  ansible.builtin.command:
    cmd: terraform init
    chdir: /tmp/gcp_deploy

- name: Provision on GCP via Terraform
  community.general.terraform:
    project_path: /tmp/gcp_deploy
    state: present
    variables:
      gcp_key: "{{ gcp_local_credentials_file }}"
      gcp_project: "{{ gcp_project }}"
      gcp_region: "{{ gcp_region }}"
      gcp_zone: "{{ gcp_zone }}"
      gcp_prefix: "{{ cloud_prefix }}"
      num_instances: "{{ num_instances }}"
      gcp_disk_image: "{{ gcp_disk_image }}"
      machine_type: "{{ machine_type }}"
      cloud_master_volume_size: "{{ cloud_master_volume_size }}"
      cloud_worker_volume_size: "{{ cloud_worker_volume_size}}"
  register: terraform_output
  no_log: true

# - name: Debug Terraform output
#   ansible.builtin.debug:
#     var: terraform_output
#   tags:
#     - debug
