---
- name: Ensure GCP Terraform Directory Exists
  ansible.builtin.stat:
    path: /tmp/gcp_deploy
  register: gcp_deploy_directory

- name: Teardown GCP infrastructure via Terraform
  community.general.terraform:
    variables:
      gcp_key: "{{ playbook_dir }}/credentials/gcp-creds.json"
      gcp_project: "eloquent-theme-264620"
    project_path: /tmp/gcp_deploy
    state: absent
  register: terraform_output
  when: gcp_deploy_directory.stat.exists and gcp_deploy_directory.stat.isdir
  no_log: true

# - name: Debug Terraform output
#   ansible.builtin.debug:
#     var: terraform_output
#   when: gcp_deploy_directory.stat.exists and gcp_deploy_directory.stat.isdir

- name: delete terraform directory
  ansible.builtin.file:
    path: /tmp/gcp_deploy
    state: absent
  when: gcp_deploy_directory.stat.exists and gcp_deploy_directory.stat.isdir
