---
- name: Ensure GCP Terraform Directory Exists
  ansible.builtin.stat:
    path: /tmp/gcp_deploy
  register: gcp_deploy_directory

- name: Teardown GCP infrastructure via Terraform
  community.general.terraform:
    variables:
      gcp_key: "{{ gcp_local_credentials_file }}"
      gcp_project: "{{ gcp_project }}"
    project_path: /tmp/gcp_deploy
    state: absent
  register: terraform_output
  when: gcp_deploy_directory.stat.exists and gcp_deploy_directory.stat.isdir
  no_log: true

# - name: Debug Terraform output
#   ansible.builtin.debug:
#     var: terraform_output
#   when: gcp_deploy_directory.stat.exists and gcp_deploy_directory.stat.isdir

- name: delete terraform directory
  ansible.builtin.file:
    path: /tmp/gcp_deploy
    state: absent
  when: gcp_deploy_directory.stat.exists and gcp_deploy_directory.stat.isdir
