---
- name: Set up Kubernetes cluster via Kubeadm
  hosts: localhost
  gather_facts: no
  vars:
    machine_type: default
  vars_files:
    - ./vars/default-vars.yml
    - ./credentials/aws-creds.yml

  tasks:

    - name: Provision on GCP via Terraform
      ansible.builtin.include_role:
        name: michaelford85.manage_k8s_gcp.manage_nodes
        tasks_from: provision_nodes.yml
      when: cloud_provider == "gcp"

    - name: Provision on AWS via Terraform
      ansible.builtin.include_role:
        name: michaelford85.manage_k8s_aws.manage_nodes
        tasks_from: provision_nodes.yml
      when: cloud_provider == "aws_ec2"
