---
roles:
  - name: geerlingguy.docker
    version: 3.1.2
  - name: geerlingguy.pip
    version: 2.1.0
  - name: geerlingguy.kubernetes
    version: 4.0.2

collections:
  - name: amazon.aws
    version: 1.5.0
  - name: google.cloud
    version: 1.0.2
  - name: community.general
    version: 3.3.1
