---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: vault
spec: {}
status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hashicorp-vault-dev
  name: hashicorp-vault-dev
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashicorp-vault-dev
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hashicorp-vault-dev
    spec:
      volumes:
      - name: vault-vol
        emptyDir: {}
      containers:
      - image: vault
        name: vault
        resources: {}
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: ansible
        ports:
        - containerPort: 8200
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hashicorp-vault-dev
  name: hashicorp-vault-dev
  namespace: vault
spec:
  type: NodePort
  ports:
  - port: 8200
    protocol: TCP
    targetPort: 8200
    nodePort: 30082
  selector:
    app: hashicorp-vault-dev
status:
  loadBalancer: {}
