---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: front-end
    owner: mford
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
        owner: mford
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 8
  selector:
    matchLabels:
      type: front-end