---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  selector:
    deployment: mysql
    app: deployment
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment
      deployment: mysql
  template:
    metadata:
      labels:
        deployment: mysql
        app: deployment
    spec:
      containers:
      - name: mysql-container
        image: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-volume
        envFrom:
        - configMapRef:
            name: wp-pass
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-pvc
