apiVersion: v1
kind: Service
metadata:
  name: nginx-frontend
  labels:
    app: nginx-frontend
spec:
  type: NodePort
  ports:
  - port: 80
    name: web
  selector:
    app: nginx-app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx-frontend"
  replicas: 5 # by default is 1
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
          name: web
