apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployment
      deployment: wordpress
  template:
    metadata:
      labels:
        deployment: wordpress
        app: deployment
    spec:
      containers:
      - name: wordpress-container
        image: wordpress
        volumeMounts:
        - mountPath: /var/www/html
          name: wp-volume
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-service
        envFrom:
        - configMapRef:
            name: wp-pass
      volumes:
      - name: wp-volume
        persistentVolumeClaim:
          claimName: wp-pvc
