apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  labels:
    app: mysql-app
spec:
  serviceName: mysql-headless-service
  replicas: 4
  selector:
    matchLabels:
      app: mysql-app
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql-app
      spec:
        containers:
        - name: mysql
          image: mysql
