---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: ClusterIP
  selector:
    deployment: webapp
    app: deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: deployment
      deployment: webapp
  template:
    metadata:
      labels:
        deployment: webapp
        app: deployment
    spec:
      containers:
      - name: webapp-container
        image: quay.io/michaelford85/simple_webapp
