---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
  labels:
    app: myapp
    owner: mford
spec:
  containers:
    - name: alpine-container
      image: alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: myapp
    owner: mford
spec:
  containers:
    - name: nginx-container
      image: nginx
